---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Skates
  title: Skates
spec:
  type: team
  profile:
    email: derry.osullivan@workday.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: derry.osullivan
spec:
  profile:
    displayName: Derry O Sullivan
    email: derry.osullivan@workday.com
    picture: https://api.dicebear.com/9.x/adventurer/svg?seed=Trouble&backgroundColor=transparent
  memberOf: [Skates]
---
apiVersion: backstage.io/v1alpha1
metadata:
  name: cloud-platform-20-system
  title: cloud platform 2
spec:
  owner: group:skates
  domain: cloud-platform-20-domain
kind: System
---
apiVersion: backstage.io/v1alpha1
metadata:
  name: s3-operator
  title: s3-operator
  description: This is the CP skates AWS S3 bucket operator
  annotations:
      pagerduty.com/integration-key: 1299cf0a6c8a4000d0101e98f7b20798
      github.com/project-slug: scylla/s3-operator
      jira/project-key: SCYLLA
      jira/component: S3 Cloud Operator
      backstage.io/techdocs-ref: url:https://ghe.megaleo.com/mathew-fleisch/backstage-spike/tree/master/packages/techdocs-cli/src/example-docs
      jfrog-artifactory/image-name: s3-operator
  links:
    - url: https://ghe.megaleo.com/scylla/s3-operator
      title: GHE Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: Skates
  system: cloud-platform-20-system
kind: Component
---
